services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/umap.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - umap_init_net

  certbot:
     image: certbot/certbot
     restart: "no"
     volumes:
       - ./certbot/conf:/etc/letsencrypt
       - ./certbot/www:/var/www/certbot
     command: >
      certonly
      --webroot
      --webroot-path=/var/www/certbot
      --email emilio.mariscal@hotosm.org
      --agree-tos
      --no-eff-email
      -d umap-dev.hotosm.org
      --keep-until-expiring
      --non-interactive
     depends_on:
      - nginx
     networks:
      - umap_init_net

networks:
  umap_init_net: