services:
  db:
    container_name: hotumap-db
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 2s
    image: postgis/postgis:14-3.4-alpine
    environment:
      - POSTGRES_DB=${UMAP_DB_NAME:-postgres}
      - POSTGRES_USER=${UMAP_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${UMAP_DB_PASSWORD:-123456}
    volumes:
      - umap_db:/var/lib/postgresql/data
      - ./custom/tilelayers.csv:/umap/tilelayers.csv
      - ./scripts/import-tilelayers.sh:/umap/import-tilelayers.sh
      - ./scripts/import-tilelayers.sql:/umap/import-tilelayers.sql

  app:
    image: umap/umap:3.1.2
    deploy:
      replicas: ${APP_REPLICAS:-4}
      resources:
        limits:
          cpus: ${APP_CPUS:-0.8}
          memory: ${APP_MEM:-3072M}
        reservations:
          cpus: "0.1"
          memory: ${APP_MEM_RES:-512M}
    environment:
      - SITE_DOMAIN=${SITE_DOMAIN:-localhost}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - UMAP_SITE_URL=${UMAP_SITE_URL:-http://127.0.0.1:8001/}
      - UMAP_SETTINGS=/srv/umap/settings.py
      - UMAP_SECRET_KEY=${UMAP_SECRET_KEY:-somelonghash}
      - UMAP_DB_HOST=${UMAP_DB_HOST:-db}
      - UMAP_DB_NAME=${UMAP_DB_NAME:-postgres}
      - UMAP_DB_USER=${UMAP_DB_USER:-postgres}
      - UMAP_DB_PASSWORD=${UMAP_DB_PASSWORD:-123456}
      - UMAP_OSM_KEY=${UMAP_OSM_KEY}
      - UMAP_OSM_SECRET=${UMAP_OSM_SECRET}
      - UMAP_SOCIAL_AUTH_REDIRECT_IS_HTTPS=${UMAP_SOCIAL_AUTH_REDIRECT_IS_HTTPS:-False}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_SECURITY_TOKEN=${S3_SECURITY_TOKEN}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - ENABLE_S3_STORAGE=${ENABLE_S3_STORAGE:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost}
    volumes:
      - ./settings.py:/srv/umap/settings.py
      - ./data:/srv/umap/var/data
      - ./custom:/srv/umap/custom
      - ./docker/entrypoint.sh:/srv/umap/docker/entrypoint.sh
      - ./urls.py:/srv/umap/urls.py
      - ./manage.py:/srv/umap/manage.py
      - ./views.py:/srv/umap/views.py
      - ./wsgi.py:/srv/umap/wsgi.py
      - ./hotumap:/srv/umap/hotumap
      - ./static:/srv/umap/static
    restart: always
    depends_on:
      db:
        condition: service_healthy

  nginx:
      image: nginx:latest
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./certbot/www:/var/www/certbot
        - ./certbot/conf:/etc/letsencrypt
        - ./static:/srv/umap/static
        - ./custom/icons:/srv/umap/custom/icons/
      depends_on:
        - app

  certbot:
      image: certbot/certbot
      volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      command: certonly --webroot --webroot-path=/var/www/certbot --email ${SITE_ADMIN_EMAIL} --agree-tos --no-eff-email --force-renewal -d ${SITE_DOMAIN}

volumes:
  umap_userdata:
  umap_db: