# Generated by Django 5.1.4 on 2025-02-26 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('umap', '0025_alter_datalayer_geojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umap.datalayer')),
            ],
        ),
    ]
