# Generated by Django 5.2.5 on 2025-10-02 18:34

import django.db.models.deletion
import umap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('umap', '0028_map_is_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=umap.models.set_storage, upload_to='media_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umap.datalayer')),
            ],
        ),
    ]
